[tool.poetry]
name = "nix.dev"
version = "0.1.0"
description = ""
authors = ["Domen Ko≈æar <domen@dev.si>"]
license = "CC BY-SA"

[tool.poetry.dependencies]
python = "^3.8"
sphinx = "4.3.0"
livereload = "2.6.3"
sphinx-book-theme = "0.1.7"
sphinx-copybutton = "0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
